export const SET_PAGE_LIST = 'SET_PAGE_LIST'

export const SET_CURRENT_PAGE_INDEX = 'SET_CURRENT_PAGE_INDEX'

export const SET_ELEMENT_LIST = 'SET_ELEMENT_LIST'

export const SET_CURRENT_ELEMENT_INDEX = 'SET_CURRENT_ELEMENT_INDEX'

export const SET_SCENE = 'SET_SCENE'

export const SET_SCALE = 'SET_SCALE'

export const SET_CURRENT_ELEMENT_CSS = 'SET_CURRENT_ELEMENT_CSS'

export const SET_DRAG_FLAG = 'SET_DRAG_FLAG'
// 用于修改动画的四个属性
export const SET_ANIMATION = 'SET_ANIMATION'

export const SET_PREVIEW_FLAG = 'SET_PREVIEW_FLAG'

export const SET_TEXT_EDIT_FLAG = 'SET_TEXT_EDIT_FLAG'

export const SET_CURRENT_ELEMENT_PROPERTIES = 'SET_CURRENT_ELEMENT_PROPERTIES'